In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(color_codes=True)

In [5]:
df=pd.read_csv("after_encoding.csv")

In [7]:
display(df.head())

,OP_CARRIER_FL_NUM,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,ARR_TIME,ARR_DELAY,AIR_TIME,...,DEST_MSP,DEST_ORD,DEST_OTHER,DEST_PHL,DEST_PHX,DEST_SAN,DEST_SEA,DEST_SFO,DEST_SLC,DEST_TPA
0,3280,601.0,1.0,22.0,623.0,714.0,8.0,722.0,-1.0,51.0,...,False,False,False,False,False,False,False,False,False,False
1,3281,1359.0,-5.0,15.0,1414.0,1629.0,4.0,1633.0,-36.0,75.0,...,False,False,True,False,False,False,False,False,False,False
2,3282,1215.0,-5.0,18.0,1233.0,1323.0,6.0,1329.0,-16.0,50.0,...,False,False,True,False,False,False,False,False,False,False
3,3283,1521.0,-6.0,14.0,1535.0,1618.0,7.0,1625.0,-14.0,43.0,...,False,False,False,False,False,False,False,False,False,False
4,3284,1847.0,-15.0,18.0,1905.0,1935.0,5.0,1940.0,-25.0,90.0,...,False,False,True,False,False,False,False,False,False,False

In [10]:
print(df.describe())

       OP_CARRIER_FL_NUM      DEP_TIME     DEP_DELAY      TAXI_OUT  \
count       7.291927e+06  7.291927e+06  7.291927e+06  7.291927e+06
mean        2.549665e+03  1.334606e+03  1.092327e+01  1.738808e+01
std         1.797284e+03  5.071999e+02  4.895964e+01  1.000148e+01
min         1.000000e+00  1.000000e+00 -8.200000e+01  1.000000e+00
25%         1.018000e+03  9.140000e+02 -5.000000e+00  1.100000e+01
50%         2.150000e+03  1.327000e+03 -2.000000e+00  1.500000e+01
75%         3.901000e+03  1.746000e+03  7.000000e+00  2.000000e+01
max         7.933000e+03  2.400000e+03  2.710000e+03  2.270000e+02

         WHEELS_OFF     WHEELS_ON       TAXI_IN      ARR_TIME     ARR_DELAY  \
count  7.291927e+06  7.291927e+06  7.291927e+06  7.291927e+06  7.291927e+06
mean   1.358255e+03  1.459074e+03  7.738977e+00  1.462998e+03  5.377757e+00
std    5.086761e+02  5.375649e+02  6.191390e+00  5.421755e+02  5.098776e+01
min    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00 -9.900000e+01
25%    9.300000e+02  1.043000e+03  4.000000e+00  1.047000e+03 -1.500000e+01
50%    1.340000e+03  1.500000e+03  6.000000e+00  1.504000e+03 -6.000000e+00
75%    1.801000e+03  1.912000e+03  9.000000e+00  1.917000e+03  7.000000e+00
max    2.400000e+03  2.400000e+03  3.160000e+02  2.400000e+03  2.695000e+03

           AIR_TIME      DISTANCE  CARRIER_DELAY  WEATHER_DELAY     NAS_DELAY  \
count  7.291927e+06  7.291927e+06   7.291927e+06   7.291927e+06  7.291927e+06
mean   1.115130e+02  8.030157e+02   4.025405e+00   7.244314e-01  3.160324e+00
std    7.045442e+01  5.941251e+02   3.002304e+01   1.420466e+01  1.849791e+01
min    4.000000e+00  3.100000e+01   0.000000e+00   0.000000e+00  0.000000e+00
25%    6.000000e+01  3.690000e+02   0.000000e+00   0.000000e+00  0.000000e+00
50%    9.300000e+01  6.410000e+02   0.000000e+00   0.000000e+00  0.000000e+00
75%    1.400000e+02  1.035000e+03   0.000000e+00   0.000000e+00  0.000000e+00
max    1.557000e+03  5.095000e+03   2.695000e+03   1.847000e+03  1.741000e+03

       SECURITY_DELAY  LATE_AIRCRAFT_DELAY       YEAR         MONTH  \
count    7.291927e+06         7.291927e+06  7291927.0  7.291927e+06
mean     1.830572e-02         5.221654e+00     2019.0  6.600330e+00
std      1.466354e+00         2.569568e+01        0.0  3.402841e+00
min      0.000000e+00         0.000000e+00     2019.0  1.000000e+00
25%      0.000000e+00         0.000000e+00     2019.0  4.000000e+00
50%      0.000000e+00         0.000000e+00     2019.0  7.000000e+00
75%      0.000000e+00         0.000000e+00     2019.0  1.000000e+01
max      1.078000e+03         2.206000e+03     2019.0  1.200000e+01

        DAY_OF_WEEK
count  7.291927e+06
mean   2.939069e+00
std    1.995826e+00
min    0.000000e+00
25%    1.000000e+00
50%    3.000000e+00
75%    5.000000e+00
max    6.000000e+00

In [12]:
numeric_cols=df.select_dtypes(include='number').columns

In [13]:
Q1=df[numeric_cols].quantile(0.25)
Q3=df[numeric_cols].quantile(0.75)
IQR=Q3-Q1

In [14]:
condition = ~((df[numeric_cols]<(Q1-1.5*IQR))|(df[numeric_cols]>(Q3+1.5*IQR))).any(axis=1)

In [16]:

df_cleaned = df[condition]

In [18]:
df_cleaned.to_csv('Outlier_removal.csv', index=False)